version: "3"
services:
  frontend:
    image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/frontend:v0.6.0@sha256:eaa077984dd8f741fc55cf75d4d3bb3f251ddb19d2b9c15cb3aea287826679d2
    ports:
      - "8080:8080"
    labels:
      application: bank-of-anthos
      environment: development
      team: frontend
      tier: web
    environment:
      - VERSION=v0.6.0
      - PORT=8080
      - ENABLE_TRACING=false
      - SCHEME=http
      - LOG_LEVEL=info
      - DEFAULT_USERNAME=admin
      - DEMO_LOGIN_USERNAME=admin
      - DEFAULT_PASSWORD=password
      - REGISTERED_OAUTH_CLIENT_ID=${REGISTERED_OAUTH_CLIENT_ID}
      - ALLOWED_OAUTH_REDIRECT_URI=${ALLOWED_OAUTH_REDIRECT_URI}
      - PUB_KEY_PATH=jwtRS256.key.pem
    volumes:
      - ./jwtRS256.key.pem:/app/jwtRS256.key.pem
  loadgenerator:
    image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/loadgenerator:v0.6.0@sha256:29b38aad1df4f7ad3293d6630b8c4bda102187b2cd3e2eff07a96b18732d2045
    labels:
      environment: development
      team: loadgenerator
      tier: test
    environment:
      - FRONTEND_ADDR=frontend:80
      - USERS=5
      - LOG_LEVEL=error
  userservice:
    image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/userservice:v0.6.0@sha256:f96d964b97cd1a9b892e18d5414365f11857cf7e878f3a653d0eb9793406e7c0
    labels:
      - "application=bank-of-anthos"
      - "environment=development"
      - "team=accounts"
      - "tier=backend"
    environment:
      - VERSION=v0.6.0
      - PORT=8080
      - ENABLE_TRACING=false
      - LOG_LEVEL=info
      - PRIV_KEY_PATH=./private_key.pem
      - PUB_KEY_PATH=./public_key.pem
      - TOKEN_EXPIRY_SECONDS=1200
      - ACCOUNTS_DB_URI=postgresql://accounts-admin:accounts-pwd@accounts-db:5432/accounts-db
    ports:
      - "8081:8080"
    volumes:
      - "./private_key.pem:/app/private_key.pem"
      - "./public_key.pem:/app/public_key.pem"
  contacts:
    image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/contacts:v0.6.0@sha256:9dbd79e095fec51e703467392423e0284038381bc740283eb0ec770053d3e545
    labels:
      - "application=bank-of-anthos"
      - "environment=development"
      - "team=accounts"
      - "tier=backend"
    environment:
      - VERSION=v0.6.0
      - PORT=8080
      - ENABLE_TRACING=false
      - LOG_LEVEL=info
      - ACCOUNTS_DB_URI=postgresql://accounts-admin:accounts-pwd@accounts-db:5432/accounts-db
      - PUB_KEY_PATH=./public_key.pem
    ports:
      - "8082:8080"
    volumes:
      - "./public_key.pem:/app/public_key.pem"
  accounts-db-config:
    image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/accounts-db:v0.6.0@sha256:4464fdf0c82bb2ad1919d25b4adfd0fb01251c117d5bf6f8041895776768cac9
    labels:
      - "application=bank-of-anthos"
      - "environment=development"
      - "team=accounts"
      - "tier=db"
    environment:
      - ACCOUNTS_DB_URI=postgresql://accounts-admin:accounts-pwd@accounts-db:5432/accounts-db
      - POSTGRES_DB=accounts-db
      - POSTGRES_PASSWORD=accounts-pwd
      - POSTGRES_USER=accounts-admin
      - USE_DEMO_DATA=True
    env_file:
      - ./environment-config.env
      - ./accounts-db-config.env
      - ./demo-data-config.env
    ports:
      - "5432:5432"
        #volumes:
        # - postgres-data:/var/lib/postgresql/data
  ledger-db-config:
    image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/ledger-db:v0.6.0@sha256:2d954418067e61edadac57bc9a9e40a9444754dce7efcd356007053a6cdb2545
    labels:
      - "application=bank-of-anthos"
      - "environment=development"
      - "team=ledger"
      - "tier=db"
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ledger-db:5432/postgresdb
      - SPRING_DATASOURCE_USERNAME=admin
      - USE_DEMO_DATA="true"
      - LOCAL_ROUTING_NUM=""
    env_file:
      - ./environment-config.env
      - ./ledger-db-config.env
      - ./demo-data-config.env
    ports:
      - "5433:5432"

  ledgerwriter:
    image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/ledgerwriter:v0.6.0@sha256:daad0e86485b97a942ca4c977efa1adee6b0149ea3c71f07df747a3f73f3b28e
    labels:
      - "application=bank-of-anthos"
      - "environment=development"
      - "team=ledger"
      - "tier=backend"
    environment:
      - VERSION=v0.6.0
      - PORT=8080
      - ENABLE_TRACING=false
      - ENABLE_METRICS=false
      - JVM_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms256m -Xmx512m
      - LOG_LEVEL=info
      - LOCAL_ROUTING_NUM=""
      - BALANCES_API_ADiDR=""
      - PUB_KEY_PATH=""
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ledger-db:5432/postgresdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - ./tmp:/tmp
      - ./keys:/tmp/.ssh:ro
    ports:
      - 8085:8080

  balancereader:
    image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/balancereader:v0.6.0@sha256:92b423f1c6e9b669b5e8a2256abdec832581e7fb04f862a84b4d8321b5609fcc
    labels:
      - "application=bank-of-anthos"
      - "environment=development"
      - "team=ledger"
      - "tier=backend"
    environment:
      - VERSION=v0.6.0
      - PORT=8080
      - ENABLE_TRACING=false
      - ENABLE_METRICS=false
      - JVM_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms256m -Xmx512m
      - LOG_LEVEL=info
      - POLL_MS=100
      - CACHE_SIZE=1000000
      - NAMESPACE=metadata.namespace
      - BALANCES_API_ADDR=""
      - PUB_KEY_PATH=""
      - LEDGER_API_ADDR=""
      - LOCAL_ROUTING_NUM=""
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ledger-db:5432/postgresdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - GOOGLE_APPLICATION_CREDENTIALS=./keys/credentials.json
    volumes:
      - ./tmp:/tmp
      - ./keys:/keys
      - ./keys/credentials.json:/keys/credentials.json:ro
    ports:
      - 8086:8080

  transactionhistory:
    image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/transactionhistory:v0.6.0@sha256:c090ad19d0b7294f523c1d38097ab17168eb08c796b0b5097a4656bb4cb8371e
    labels:
      - "application=bank-of-anthos"
      - "environment=development"
      - "team=ledger"
      - "tier=backend"
    environment:
      - VERSION=v0.6.0
      - PORT=8080
      - ENABLE_TRACING=false
      - ENABLE_METRICS=false
      - JVM_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms256m -Xmx512m
      - LOG_LEVEL=info
      - LOCAL_ROUTING_NUM=""
      - BALANCES_API_ADDR=""
      - PUB_KEY_PATH=""
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ledger-db:5432/postgresdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
       - GOOGLE_APPLICATION_CREDENTIALS=./keys/credentials.json
    volumes:
      - ./tmp:/tmp
      - ./keys:/keys
      - ./keys/credentials.json:/keys/credentials.json:ro
    ports:
      - 8083:8080
