version: "3"
services:
   ledger-db-config:
    image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/ledger-db:v0.6.0@sha256:2d954418067e61edadac57bc9a9e40a9444754dce7efcd356007053a6cdb2545
    labels:
      application: bank-of-anthos
      environment: development
      team: ledger
      tier: db
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ledger-db:5432/postgresdb
      - SPRING_DATASOURCE_USERNAME=admin
      - USE_DEMO_DATA="true"
      - LOCAL_ROUTING_NUM=""
    env_file:
      - ./environment-config.env
      - ./ledger-db-config.env
      - ./demo-data-config.env
    ports:
      - "5433:5432"
   balancereader:
    image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/balancereader:v0.6.0@sha256:92b423f1c6e9b669b5e8a2256abdec832581e7fb04f862a84b4d8321b5609fcc
    labels:
      application: bank-of-anthos
      environment: development
      team: ledger
      tier: backend
    environment:
      - VERSION=v0.6.0
      - PORT=8080
      - ENABLE_TRACING=false
      - ENABLE_METRICS=false
      - JVM_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms256m -Xmx512m
      - LOG_LEVEL=info
      - POLL_MS=100
      - CACHE_SIZE=1000000
      - NAMESPACE=metadata.namespace
      - BALANCES_API_ADDR=""
      - PUB_KEY_PATH=""
      - LEDGER_API_ADDR=""
      - LOCAL_ROUTING_NUM=""
      - SPRING_DATASOURCE_URL="jdbc:postgresql://ledger-db:5432/postgresdb"
      - SPRING_DATASOURCE_USERNAME="admin"
      - SPRING_DATASOURCE_PASSWORD="password"
      - GOOGLE_APPLICATION_CREDENTIALS=./keys/credentials.json
        # - spring.cloud.gcp.credentials=./keys/credentials.json
    volumes:
      - ./tmp:/tmp
      - ./keys:/keys
    # Add the following line to mount the credentials file
      - ./keys/credentials.json:/keys/credentials.json:ro
    ports:
      - 8086:8080
